### ISSUE TITLE
sudo: cargo: command not found

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#3] opened 2018-06-11 17:55 UTC
When I come to the step

    sudo -u ff-node-monitor cargo build --release

I get the error 

    sudo: cargo: command not found

I tried on Debian stretch and on jessie plain install.

**Comment by RalfJung** [comment] 2018-06-11 18:10
Hm indeed, I can reproduce. Seems like the PATH isn't picked up. Does this work?
```
sudo -u ff-node-monitor /var/lib/ff-node-monitor/.cargo/bin/cargo build --release
```

**Comment by rubo77** [comment] 2018-06-11 21:52
yes, that works

**Comment by rubo77** [comment] 2018-06-11 21:58
I had to `apt install gcc` to make it compile

**Comment by rubo77** [comment] 2018-06-11 21:59
In the beginning I had to install `curl`, so maybe add this too to the readme

**Comment by rubo77** [comment] 2018-06-11 22:02
Außerdem musste ich das Paket `pkg-config` installieren, damit er den Pfad zu OpenSSL finden kann beim compilieren

**Comment by rubo77** [comment] 2018-06-11 22:09
Also auf Debian stretch:

    apt install curl gcc pkg-config libssl-dev libpq-dev postgresql

But in the end Now I get this error:

```
error[E0432]: unresolved import `syntax::parse::common`
 --> /var/lib/ff-node-monitor/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_codegen-0.3.12/src/utils/parser_ext.rs:5:20
  |
5 | use syntax::parse::common::SeqSep;
  |                    ^^^^^^ Could not find `common` in `parse`

error[E0624]: method `parse_seq_to_end` is private
  --> /var/lib/ff-node-monitor/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_codegen-0.3.12/src/utils/parser_ext.rs:13:14
   |
13 |         self.parse_seq_to_end(&Eof,
   |              ^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

**Comment by rubo77** [comment] 2018-06-11 22:21
Ev. muss das so heissen?

    use syntax::parse::SeqSep;

also ohne `common::`

**Comment by RalfJung** [comment] 2018-06-12 08:55
Thanks, I updated the build instructions to fix the path to cargo and add the missing packages.

> But in the end of compilation, I get this error:

Rocket is unfortunately broken with current Rust nightly, which is tracked at https://github.com/SergioBenitez/Rocket/issues/660. You can either wait until https://github.com/rust-lang/rust/pull/51502 lands (which fixes the problem), or use an older nightly:
```
$ sudo -u ff-node-monitor /var/lib/ff-node-monitor/.cargo/bin/rustup default nightly-2018-06-09
```

I am going to close this issue because the build issue is unrelated.

**Closed by RalfJung** 2018-06-12 08:55 UTC
Labels: bug

**Comment by rubo77** [comment] 2018-06-12 09:06
OK i restart with

```
sudo -u ff-node-monitor /var/lib/ff-node-monitor/.cargo/bin/rustup default nightly-2018-06-09
cd /var/lib/ff-node-monitor/src/
sudo -u ff-node-monitor /var/lib/ff-node-monitor/.cargo/bin/cargo build --release
```
